[package]
name = "iec-interpreter"
version = "0.1.0"
authors = ["NOP0 <33583294+NOP0@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
